### ISSUE TITLE
Nice start, what made you choose upflow?

### ISSUE THREAD

**Issue by barnaby** [karlhorky/upflow-landing-clone-may-2020#3]

**Comment by karlhorky** [comment]
Hey Barnaby, thanks for the encouraging words! I chose Upflow from [Landingfolio](https://www.landingfolio.com/) because it seemed like a good demo of styling with CSS for me to show our students at @upleveled (learning [Emotion](https://emotion.sh/docs/introduction)!). Will also reach out over Twitter DMs, happy to chat further!
